language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r test_requirements.txt . --use-mirrors
# command to run tests
before_script:
  - psql -c 'create database coaster_test;' -U postgres
script: coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
