sudo: false
language: python
cache: pip
python:
  - "2.7"
addons:
  postgresql: "9.4"
services:
  - postgresql
# command to install dependencies
install:
  - pip install -r test_requirements.txt . --use-mirrors
# command to run tests
before_script:
  - psql -c 'create database coaster_test;' -U postgres
script: coverage run `which nosetests`
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
